Desktop app can compile and load into programming module
Kidtronics/DesktopApp pull request #2
Opened 2018-08-04 18:39 UTC by baixiaobest

2018-08-06 03:48 UTC, baiyu123 commented on arduino_files/test_led/LEDArrayConnection.h
> +	char m_LEDState;
Add a documentation on this

2018-08-06 04:01 UTC, baiyu123 commented on arduino_files/test_led/Message.h
> + * ParsedMessage.h
need documentation, where and how to use this class.

2018-08-06 04:05 UTC, baiyu123 commented on arduino_files/test_led/MessageParser.cpp
> +//bool MessageParser::isCorrupted() {
Delete this function

2018-08-06 04:06 UTC, baiyu123 commented on arduino_files/test_led/SerializerUtils.cpp
> +//    strncat(buffer, &ESCAPE_CHAR,1);
delete it

2018-08-06 04:07 UTC, baiyu123 commented on arduino_files/test_led/SerializerUtils.cpp
> +//    DataType dataType = getDataType<T>(input);
delete

2018-08-06 04:07 UTC, baiyu123 commented on arduino_files/test_led/SerializerUtils.cpp
> +//    strncat(buffer, &ESCAPE_CHAR,1);
delete

2018-08-06 04:07 UTC, baiyu123 commented on arduino_files/test_led/SerializerUtils.cpp
> +//DataType StringVariable::getDataType(T &input)
delete

2018-08-06 04:07 UTC, baiyu123 commented on arduino_files/test_led/SerializerUtils.h
> +//#include <typeinfo>
delete

2018-08-06 04:08 UTC, baiyu123 commented on arduino_files/test_led/SerializerUtils.h
> +//    template<typename T>
delete

2018-08-06 04:13 UTC, baiyu123 requested changes
Good

2018-08-10 04:14 UTC, baixiaobest commented on arduino_files/test_led/LEDArrayConnection.h
> +	char m_LEDState;
Comment is on the top of this file.

2018-08-10 08:45 UTC, baiyu123 approved these changes

2018-08-10 08:45 UTC, merged